spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud

  #jpa:
  #  generate-ddl: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1858131357887980
            clientSecret: 50e8ff03070f47fbf9fdfe86a5fdc55a
            scope: email, public_profile
          google:
            clientId: 1858131357887980
            clientSecret: 50e8ff03070f47fbf9fdfe86a5fdc55a
            scope: email, public_profile
server:
  port: 8443
  ssl:
    key-store: file:/Users/monked/monkar/estudios/springInAction/spring_in_action/mykeys.jks
    key-store-password: malditoperu
    key-password: malditoperu


logging:
  file:
    name: /Users/monked/monkar/logs/TacoCloud.log
  level:
    root: INFO
    org:
      springframework:
        security: INFO


taco:
  orders:
    pageSize: 20