spring:
  thymeleaf:
    cache: false

  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: recreate
      local-datacenter: datacenter1
      username: monkar
      password: monkar

